---
- hosts: all
  become: true
  remote_user: root
  
  tasks:
  - name: Disable Password Authentication
    lineinfile:    
      dest: /etc/ssh/sshd_config    
      regex: '^PasswordAuthentication'    
      line: "Password Authentication no"    
      state: present    
      backup: yes

  - name: Install packages
    apt:
      pkg:
      - haproxy
      - docker.io
      state: present

  - name: Copy haproxy config
    ansible.builtin.copy:
      src: haproxy.cfg
      dest: /root/haproxy.cfg
      owner: root
      group: root
      mode: '0644'


      # - name: Copy application Example
      #   ansible.builtin.copy:
      #     src: docker
      #     dest: /root/docker
      #     owner: root
      #     group: root
      #     mode: '0644'
  
      # - name: Run nginx image in docker container
      #   docker:
      #     name: nginx-container
      #     image: nginx
      #     state: reloaded
      #     ports:
      #     - "8080:80"
